// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicMakerProgram.Data;

namespace MusicMakerProgram.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20211217074736_updateDb")]
    partial class updateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MusicMakerProgram.Models.Admin", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("username");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.CanView", b =>
                {
                    b.Property<int>("cvID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("gUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pID")
                        .HasColumnType("int");

                    b.HasKey("cvID");

                    b.ToTable("canViews");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Cellist", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("name");

                    b.ToTable("Cellists");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Class", b =>
                {
                    b.Property<int>("classID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("numberOfStudents")
                        .HasColumnType("int");

                    b.Property<string>("tName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("classID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Composer", b =>
                {
                    b.Property<string>("cName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("period")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cName");

                    b.ToTable("Composers");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.GroupCanEdit", b =>
                {
                    b.Property<int>("gceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adminUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gID")
                        .HasColumnType("int");

                    b.HasKey("gceID");

                    b.ToTable("GroupCanEdits");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.GroupPerforms", b =>
                {
                    b.Property<int>("gpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("gID")
                        .HasColumnType("int");

                    b.Property<int>("perfID")
                        .HasColumnType("int");

                    b.HasKey("gpID");

                    b.ToTable("_GroupPerforms");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Guest", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("username");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Knows", b =>
                {
                    b.Property<int>("KnowsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("performerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pieceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KnowsID");

                    b.ToTable("_Knows");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Level", b =>
                {
                    b.Property<int>("levelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("yearsOfExpirience")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("levelID");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Manages", b =>
                {
                    b.Property<int>("ManagesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adminUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("classID")
                        .HasColumnType("int");

                    b.HasKey("ManagesID");

                    b.ToTable("_Manages");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Performance", b =>
                {
                    b.Property<int>("perfID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("pID")
                        .HasColumnType("int");

                    b.Property<string>("perf_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("piece_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("perfID");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Performer", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("classID")
                        .HasColumnType("int");

                    b.Property<int>("levelID")
                        .HasColumnType("int");

                    b.HasKey("name");

                    b.ToTable("Performers");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Pianist", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("name");

                    b.ToTable("Pianists");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Piece", b =>
                {
                    b.Property<string>("pName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("c_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("date")
                        .HasColumnType("int");

                    b.Property<string>("genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("musicSheetLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pName");

                    b.ToTable("Pieces");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Quartet", b =>
                {
                    b.Property<int>("gID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cellist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstViolin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("secondViolin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("violist")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("gID");

                    b.ToTable("Quartet");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Teacher", b =>
                {
                    b.Property<int>("tID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("school")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tID");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Team", b =>
                {
                    b.Property<int>("teamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("bio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("teamID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Trio", b =>
                {
                    b.Property<int>("gID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cellist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pianist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("violinist")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("gID");

                    b.ToTable("Trios");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Violinist", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("name");

                    b.ToTable("Violinists");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.Violist", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("name");

                    b.ToTable("Violists");
                });

            modelBuilder.Entity("MusicMakerProgram.Models._Program", b =>
                {
                    b.Property<int>("ProgID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumPerformers")
                        .HasColumnType("int");

                    b.HasKey("ProgID");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("MusicMakerProgram.Models.composerCanEdit", b =>
                {
                    b.Property<int>("cceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adminUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cceID");

                    b.ToTable("composerCanEdits");
                });
#pragma warning restore 612, 618
        }
    }
}
